version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
